### ISSUE TITLE
Could not run `rake db:migrate`

### ISSUE THREAD

**Issue by sergio1990** [alterego-labs/feature_db_rails#1]
## Problem

The migration process fails with the following error stack:

```
ctiveRecord::NoDatabaseError: Unknown database '_feature_do_all_awesome'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/mysql2_adapter.rb:23:in `rescue in mysql2_connection'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/mysql2_adapter.rb:10:in `mysql2_connection'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:440:in `new_connection'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:450:in `checkout_new_connection'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:424:in `acquire_connection'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_adapters/abstract/connection_pool.rb:573:in `retrieve_connection'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/connection_handling.rb:87:in `connection'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/migration.rb:941:in `initialize'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/migration.rb:823:in `new'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/migration.rb:823:in `up'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/migration.rb:801:in `migrate'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/tasks/database_tasks.rb:139:in `migrate'
/Users/sergio/.rvm/gems/ruby-2.4.1/gems/activerecord-4.2.9/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <main>'
/Users/sergio/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/sergio/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by sergio1990** [comment]
After the research, I've found that `ConnectionPool` is [initialized with the connection specification](https://github.com/rails/rails/blob/v4.2.9/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L233) BEFORE initializers are loaded and evaluated. Therefore, the base database name in the config object is nil.
